import java.util.Arrays;
import java.util.HashSet;
import java.util.Random;
import java.util.Collections;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int rolls) {
        int[] arr = new int[rolls];
        Random rand = new Random();

        for (int i = 0; i < rolls; i++){
            arr[i] = rand.nextInt(6) + 1;
        }
        return arr;
    }

    public static boolean containsDuplicates(int[] arr) {

        for (int i = 0; i < arr.length; i++){
            for (int j = 0; j < arr.length; j++){
                if(i != j) {
                    if (arr[i] == arr[j]) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    public static int calculateAverage(int[] arr){

        int total = 0;
        for (int item : arr) {
            total += item;
        }
        return total/arr.length;
    }

    public static int[] calculateArrAverage(int[][] arr){

        int lowest = calculateAverage(arr[0]);
        int lowIndex = 0;
        int average = 0;

        for (int i = 0; i < arr.length; i++){
            average = calculateAverage(arr[i]);
            if (average < lowest) {
                lowest = average;
                lowIndex = i;
            }
        }
        return arr[lowIndex];
    }

    public static void weatherData(int[][] array) {

        HashSet<Integer> set = new HashSet<>();
        
        for (int i  = 0; i < array.length; i++) {
            for (int item : array[i]) {
                set.add(item);
            }
        }

        System.out.println("The Low was: " + Collections.min(set));
        System.out.println("The high was: " + Collections.max(set));

        for (int i = Collections.min(set); i < Collections.max(set); i++){
            if (!set.contains(i)){
                System.out.println("Never saw: " + i);
            }
        }
    }

    public static void main (String[] args) {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        weatherData(weeklyMonthTemperatures);
    }
}
