/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant {

    private String name;
    private int stars;
    private String price;

    public Restaurant (String name, int stars, String price) {
        this.name = name;
        this.stars = stars;
        this.price = price;
    }

    // Method toString outputs the name, rating, and price of a restaurant
    public String toString(){
        return this.name + " is rated " + this.stars + " and priced at " + this.price;
    }
}
