/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testLinter() {
        Path gates  = Paths.get("resources/gates.js");
        Path empty  = Paths.get("resources/empty.js");
        Path fewErrors  = Paths.get("resources/fewErrors.js");
        Path manyErrors  = Paths.get("resources/manyErrors.js");
        Path noError  = Paths.get("resources/noError.js");
        Path oneError  = Paths.get("resources/oneError.js");

        assertEquals(42, App.linter(gates));
        assertEquals(0, App.linter(empty));
        assertEquals(5, App.linter(fewErrors));
        assertEquals(34, App.linter(manyErrors));
        assertEquals(0, App.linter(noError));
        assertEquals( 1, App.linter(oneError));
    }
}
