import java.nio.file.FileSystems;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        //mess with the image
        if (args.length == 0){
            System.out.println("Oops! Something went wrong. Read the docs for more information");
        } else {
            //find a bitmap
            Path imagePath = FileSystems.getDefault().getPath("resources", args[0]);
            Path output = FileSystems.getDefault().getPath("resources", args[1]);

            //read the image
            Bitmap image = new Bitmap(imagePath, output, args[2]);

            if (image.transform == "flipHorizontally") {
                image.flipHorizontally();
                System.out.println("Success! Your image was flipped horizontally.");
            } else if (image.transform == "flipVertically"){
                image.flipVertically();
                System.out.println("Success! Your image was flipped vertically.");
            } else if (image.transform == "invert") {
                System.out.println("Success! Your image was inverted.");
                image.invert();
            } else if (image.transform == "randomize") {
                System.out.println("Success! Your image was randomized.");
                image.randomize();
            } else {
                System.out.println(args[2] + " is not available.");
            }
            //output the file
            image.save();
        }
    }
}
