/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.LinkedList;
import java.util.List;

import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void testToString() {


        //Create a review
        Review oneReview = new Review("It's alright.", "Jessica", 3);

        //add review to list
        List<Review> reviews = new LinkedList<>();
        reviews.add(oneReview);

        //update reviews
        Restaurant one = new Restaurant("Applebees", 3, "$$");

        assertEquals("Applebees is rated 3 and priced at $$", one.toString());
    }

    @Test public void testReviewToString() {
//        assertEquals("Jessica rated this restaurant 3 stars\n Review: 'It's alright.'", one.toString());
    }

    @Test public void testAddReview() {

        Restaurant one = new Restaurant("Applebees", 3, "$$");

        Review oneReview = new Review("It's alright.", "Jessica", 3);
        Review twoReview = new Review ("My favorite place to be be!", "Igor", 5);
        one.addReview(oneReview);
        one.addReview(twoReview);

        one.getReviews();
        System.out.println(one.toString());
    }
}
